output-format = "concise"
target-version = "py312"
line-length = 120

include = ["src/**/*.py", "tests/**/*.py"]

exclude = [
    ".git",
    ".venv",
    "dist",
    "docs",
    "scripts",
    "static"
]

[lint]
select = ["F401"]
ignore = []
fixable = ["ALL"]
unfixable = []
