name: Publish Docker image

permissions:
  contents: read
  packages: write

env:
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || 'docker.io' }}
  DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME || 'weboftrust/keria' }}

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g. 0.2.0)"
        required: true
      latest:
        description: "Publish :latest tag"
        type: boolean
        required: false
        default: false
      dryrun:
        description: "Dry run, don't push"
        type: boolean
        required: false
        default: false

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v4

      - name: Log in to container registry ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@v3
        with:
          # Uses github tokens for GHCR, otherwise configured repository secrets
          # This way, forks can be configured to push their own images without
          # having to modify the workflow.
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY == 'ghcr.io' && github.actor || secrets.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_REGISTRY == 'ghcr.io' && secrets.GITHUB_TOKEN || secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=${{ github.run_id }},prefix=build-
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' && inputs.latest == true }}
            type=raw,value=${{ inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && inputs.version != '' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'workflow_dispatch' || inputs.dryrun != true }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
